title: Generated Battle Scenario
orb_radius: 40.0
pickup_radius: 20.0
arena_width: 800
arena_height: 800
fps: 60
orbs:
  - name: Paris Saint-Germain
    logo: assets/logos/psg.svg.webp
    max_hp: 6
    outline_color:
      - 255
      - 0
      - 0
    initial_position:
      - 200.0
      - 400.0
    initial_velocity:
      - 185.92
      - 46.98
  - name: Inter Milan
    logo: assets/logos/inter.svg.png
    max_hp: 6
    outline_color:
      - 0
      - 0
      - 255
    initial_position:
      - 600.0
      - 400.0
    initial_velocity:
      - -173.61
      - -25.54
events:
  - t: 2.23
    type: spawn_pickup
    kind: saw
    x: 176.87022062733553
    y: 177.66840419012405
  - t: 9.67
    type: slowmo
    factor: 0.2
    duration: 5.632706063004081
  - t: 13.88
    type: spawn_pickup
    kind: heart
    x: 192.08207135203278
    y: 433.52251355538874
  - t: 19.15
    type: spawn_pickup
    kind: shield
  - t: 25.73
    type: spawn_pickup
    kind: shield
  - t: 31.55
    type: spawn_pickup
    kind: saw
    x: 58.838004516835475
    y: 415.4398833574551
  - t: 37.15
    type: spawn_pickup
    kind: saw
    x: 586.6487865905925
    y: 165.55254015670116
  - t: 42.23
    type: spawn_pickup
    kind: heart
    x: 147.74233242581283
    y: 580.4925611851152
  - t: 48.78
    type: slowmo
    factor: 0.2
    duration: 5.883445019666838
  - t: 52.92
    type: spawn_pickup
    kind: shield
  - t: 59.7
    type: spawn_pickup
    kind: heart
    x: 151.36639916507042
    y: 574.8228303542182
  - t: 63.87
    type: spawn_pickup
    kind: saw
    x: 610.8335720285851
    y: 470.9243965697323
  - t: 67.93
    type: spawn_pickup
    kind: heart
    x: 470.3980778921174
    y: 473.1420485643358
