events:
  - { t: 2,  type: spawn_pickup, kind: "heart", x: 0.5, y: 0.5 } # Relative to arena size
  - { t: 3,  type: spawn_pickup, kind: "saw", x: 200, y: 300 }   # Absolute pixels in arena
  - { t: 5,  type: text_overlay, text: "Slow Mo Incoming!", duration: 2, position: "top_center", font_size: 60 }
  - { t: 7, type: slowmo, factor: 0.3, duration: 4 }
  - { t: 12, type: text_overlay, text: "MAXIMUM SPEED!", duration: 3, position: [0.5, 0.2], color: [255,50,50] } # Relative to canvas, red
  - { t: 15, type: spawn_pickup, kind: "heart" } # Random position