# General game settings
seed: 42
title: "Epic Orb Battle - High Drama"
duration: 60 # Overall video duration in seconds (plan_story uses duration-5 for HP events)

# Story planning specific settings
drama_level: "high" # Can be "high", "normal", or "low"
story_seed: 12345 # Separate seed for story generation to make stories reproducible

# Orb definitions
orbs:
  - name: "PSG"
    logo: "assets/logos/psg.svg.webp" # Replace with actual path to logo
    max_hp: 20
    outline_color: [255, 100, 100] # Reddish outline

  - name: "INTER"
    logo: "assets/logos/inter.svg.png" # Replace with actual path to logo
    max_hp: 20
    outline_color: [100, 150, 255] # Bluish outline

  # You can add more orbs if your game logic supports more than two,
  # but plan_story currently assumes the first two are the main combatants.
  # - name: "Forest"
  #   logo: "assets/logos/orb_green.png"
  #   max_hp: 15
  #   outline_color: [100, 255, 100]

# --- Optional: If you wanted to mix plan_story with other scripted events ---
# If you modify Director to load from file AND then add plan_story events,
# you could have a section like this.
# The current battle.py initializes Director only with plan_story events if 2+ orbs exist.
#
# events:
#   - t: 5.0
#     type: text_overlay
#     payload:
#       text: "Round 1"
#       duration: 2
#       position: top_center
#       color: [255, 255, 0] # Yellow
#       font_size: 72
#
#   - t: 10.0
#     type: spawn_pickup
#     payload:
#       kind: "saw" # 'saw' or 'heart'
#       x: 0.5 # Relative position (0.0 to 1.0) or absolute pixels
#       y: 0.2 # Relative position (0.0 to 1.0) or absolute pixels
#
#   - t: 15.0
#     type: slowmo
#     payload:
#       factor: 0.3 # Game speed multiplier (e.g., 0.5 is half speed)
#       duration: 3.0 # How long the slowmo effect lasts in game seconds
